### PR TITLE
Cleaned up a bit.

### PR DESCRIPTION
**Pull request by Piehthyte**
Cleaned the code up a bit to make it more pretty to the eye! It already
was but its just an improvement. Also removed any unused statements that
were actually in the code.

### CODE REVIEW

**Comment by Technoguyfication** [comment]
I'll merge it but if it starts breaking I know who to look at XD

**Comment by Piehthyte** [comment]
Haha if it broke just delete the pull request and roll back! XD

**Comment by Technoguyfication** [comment]
It's reverted, it was breaking by making everything internal and hard to read :P

**Comment by Piehthyte** [comment]
XD I know what I did wrong :p dunno why it all being internal broke it! That should speed it up...

**Comment by Technoguyfication** [comment]
Not exactly sure what happened, but once I get everything functional I will start working on cleaning up all the spaghetti code

**Pull request merged**
